# Generated by Django 4.2.25 on 2025-12-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Subtitle"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="projects/", verbose_name="Image"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        help_text="Comma separated: Python, Django, React",
                        max_length=300,
                        verbose_name="Tags",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Project URL")),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub URL")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
