# Generated by Django 4.2.25 on 2025-12-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Excerpt"
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="blog/", verbose_name="Image"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        help_text="Comma separated", max_length=300, verbose_name="Tags"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                ("published_at", models.DateTimeField(verbose_name="Published at")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
